[package]
name = "aws_ec2_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.23.0", features = ["macros", "rt"] }
tokio-stream = "0.1.8"
anyhow = "1.0.66"
num-traits = "0.2.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tracing-subscriber = "0.3.16"

aws-sdk-ec2 = "0.22.0"
aws-sdk-pricing = "0.22.0"

aws-config = "0.52.0"
aws-types = "0.52.0"
aws-smithy-types-convert = {version = "0.52.0", features = ["convert-chrono"] }