[package]
name = "aws_ec2_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.28.2", features = ["macros", "rt"] }
tokio-stream = "0.1.12"
anyhow = "1.0.71"
num-traits = "0.2.14"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.95"
tracing-subscriber = "0.3.17"

aws-sdk-ec2 = "0.27.0"
aws-sdk-pricing = "0.27.0"

aws-config = "0.55.2"
aws-types = "0.55.2"
aws-smithy-types-convert = {version = "0.55.2", features = ["convert-chrono"] }