[package]
name = "aws_ec2_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.34.0", features = ["macros", "rt"] }
anyhow = "1.0.75"
num-traits = "0.2.17"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.108"
tracing-subscriber = "0.3.17"

pretty_assertions = "1.4.0"

aws-sdk-ec2 = "0.35.0"
aws-sdk-pricing = "0.35.0"

aws-config = "0.57.1"
aws-types = "0.57.1"
aws-smithy-types-convert = {version = "0.57.1", features = ["convert-chrono"] }
