[package]
name = "aws_ec2_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.32.0", features = ["macros", "rt"] }
tokio-stream = "0.1.12"
anyhow = "1.0.71"
num-traits = "0.2.16"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
tracing-subscriber = "0.3.17"

pretty_assertions = "1.4.0"

aws-sdk-ec2 = "0.29.0"
aws-sdk-pricing = "0.29.0"

aws-config = "0.56.0"
aws-types = "0.56.0"
aws-smithy-types-convert = {version = "0.56.0", features = ["convert-chrono"] }