[package]
name = "aws_ec2_analyzer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.18.0", features = ["macros", "rt"] }
tokio-stream = "0.1.8"
rusqlite = "0.28.0"
anyhow = "1.0.66"
num-traits = "0.2.14"
pretty_assertions = "1.1.0"
chrono = { version = "0.4.19", default-features = false}
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
tera = { version = "1.11.0", default-features = false }
itertools = "0.10.4"
tracing-subscriber = "0.2.20"
rand = "0.8.5"

aws-sdk-ec2 = "0.21.0"
aws-sdk-pricing = "0.21.0"

aws-config = "0.51.0"
aws-types = "0.51.0"
aws-smithy-types-convert = {version = "0.51.0", features = ["convert-chrono"] }